### ISSUE TITLE
Requests to the API are not aborted when changing the dashboard

### ISSUE THREAD

**Issue by xafilox** [SmartDeveloperHub/sdh-web#11]
When an observe is stopped, all its pending requests should be cancelled.

**Comment by cblanco** [comment]
Ok

**Comment by AlejandroVera** [comment]
Now the framework cancels pending requests but it is also needed to check whether the API handles aborted requests or not

**Comment by AlejandroVera** [comment]
Now the framework cancels pending requests c72a8acd2c55289a6305991be9b0906f065cf61d It is also needed to check whether the API handles aborted requests or not

**Comment by AlejandroVera** [comment]
Now the framework cancels pending requests but it is also needed to check whether the API handles aborted requests or not c72a8acd2c55289a6305991be9b0906f065cf61d

**Comment by xafilox** [comment]
Now the framework cancels pending requests (SmartDeveloperHub/sdh-framework@c72a8acd2c55289a6305991be9b0906f065cf61d) but it is also needed to check whether the API handles aborted requests or not

**Comment by cblanco** [comment]
Fixed https://github.com/SmartDeveloperHub/sdh-api/commit/e1f6dc5b810a2c58f474e5c1f049d8cd4f0d58ca
