### ISSUE TITLE
Error loading developer dashboard

### ISSUE THREAD

**Issue by cblanco** [SmartDeveloperHub/sdh-web#18]
I've only seen that in avera dashboard 

![image](https://cloud.githubusercontent.com/assets/3510628/13009270/d84a6672-d19b-11e5-9541-55a0ebcf8ae5.png)

**Comment by cblanco** [comment]
This only happens when I use real data if load a data backup does not fail

**Comment by xafilox** [comment]
@cblanco I have tried to reproduce this problem in the demo and I wasn't able. Did you do something special or is just when loading the dashboard?

**Comment by cblanco** [comment]
I could not repeat it.
It must have been a temporary glitch with my local SDH-API.
