### ISSUE TITLE
Product labels are not aligned

### ISSUE THREAD

**Issue by fserena** [SmartDeveloperHub/sdh-web#2]
![image](https://cloud.githubusercontent.com/assets/2788595/12941535/b944bbb6-cfd3-11e5-87f3-b5e47548d65e.png)

**Comment by cblanco** [comment]
![image](https://cloud.githubusercontent.com/assets/3510628/12952532/0f1d2e4a-d017-11e5-9232-7b7b056dff1e.png)

**Comment by cblanco** [comment]
Fixed. eb5c201ce2e74b5325ed1a6a82d0d73eec1cec1f
