### ISSUE TITLE
Font size in pop-ups is too big

### ISSUE THREAD

**Issue by fserena** [SmartDeveloperHub/sdh-web#3]
![image](https://cloud.githubusercontent.com/assets/2788595/12941576/2c950d78-cfd4-11e5-975c-375a2b10375f.png)

**Comment by cblanco** [comment]
![image](https://cloud.githubusercontent.com/assets/3510628/12947345/e4cef892-cffa-11e5-9f91-a95dd588a0f5.png)

**Comment by cblanco** [comment]
Fixed. 73677d5c3bd3dea91dc9f415090bcde1493dc603
