### ISSUE TITLE
External and internal developers should appear in different rows

### ISSUE THREAD

**Issue by fserena** [SmartDeveloperHub/sdh-web#4]
![image](https://cloud.githubusercontent.com/assets/2788595/12941599/6ae8f292-cfd4-11e5-8b64-bfd9c697a68c.png)

**Comment by cblanco** [comment]
Fixed. https://github.com/SmartDeveloperHub/sdh-web/commit/ba8622f6809d8d49adf888ea5d67600bb53f88d9
