### ISSUE TITLE
the product selector width is too narrow, even when it has space enough to expand

### ISSUE THREAD

**Issue by ignaciomolina** [SmartDeveloperHub/sdh-web#6]
Issue detected using Firefox, it does not happen in Chrome

**Comment by ignaciomolina** [comment]
![captura de pantalla de 2016-02-10 09 28 08](https://cloud.githubusercontent.com/assets/10563987/12942137/e11e625e-cfd8-11e5-9b69-b10c9e738eaf.png)

**Comment by ignaciomolina** [comment]
![captura de pantalla de 2016-02-10 09 28 43](https://cloud.githubusercontent.com/assets/10563987/12942143/ea565f02-cfd8-11e5-8935-3c90ee526471.png)

**Comment by ignaciomolina** [comment]
it happens the same with manager selector

**Comment by cblanco** [comment]
This problem happens in Director Dashboard (2 tables) and P.Manager Dashboard (Project selector table)

**Comment by cblanco** [comment]
Fixed. ca363da725c1f01667b584d813fbfa82ee1ad063
