### ISSUE TITLE
In the product Analysis chart there are not axis colors when using Firefox

### ISSUE THREAD

**Issue by ignaciomolina** [SmartDeveloperHub/sdh-web#7]
![captura de pantalla de 2016-02-10 09 28 31](https://cloud.githubusercontent.com/assets/10563987/12942128/cbbd235a-cfd8-11e5-9e81-bd8b7b50c14b.png)

**Comment by cblanco** [comment]
It is not clear where the problem is. Maybe a D3 bug in firefox. We will study a solution.

**Comment by cblanco** [comment]
I have found no solution for now. wantfix label added
