### ISSUE TITLE
popups in product analysis chart appears even when the mouse is not directly over an item 

### ISSUE THREAD

**Issue by ignaciomolina** [SmartDeveloperHub/sdh-web#8]
behaviour observed using Firefox

**Comment by cblanco** [comment]
We have not solution for this issue by the moment. D3 Voronoi behavior is different between browsers. You can see in this snapshot the voronoi active area for each element in Firefox:
![image](https://cloud.githubusercontent.com/assets/3510628/12976699/4bbda83e-d0c6-11e5-8399-dbd663d2c706.png)
